services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    env_file:
      - /env/.kavita-env
    volumes:
      - /containers/kavita/config:/config
      - /containers/kavita/data:/data #optional
    ports:
      - 5000:5000
    restart: unless-stopped
